### PR TITLE
Resistor value corrected

### PR DESCRIPTION
**Pull request by Arrroz**

### CODE REVIEW

**Review by G-Pereira — CHANGES_REQUESTED** [review]
We should wait for #27 to review calculations

**Comment by G-Pereira** [comment]
Change transistor to 2N7002 I've re-done the calculations @Sleepy105 has made and they were wrong.
My calculations:
RdsON @ 150mA = 3.5 ohm (datasheet)
Junction to ambient thermal resistance (with 1''x1'' pad) = 241 ºC/W (datasheet)
Temperature rise = (3.5 * (0.150)^2)*241 = 17 ºC
Device would run at 42ºC which is inside recommended values (-55ºC to +150ºC)
The resistance in this case would be 18 Ohm

**Comment by G-Pereira** [comment]
I am adding a 0 ohm resistor in parallel with the transistor that is not meant to be assembled just in case we want to switch to an always on configuration.

**Review by G-Pereira — DISMISSED** [review]
Values are all ok and there is very detailed documentation about this in the Wiki. It's all good to me!
https://github.com/ieeeupsb/rasbot/wiki/IR-Matrix

**Comment by Sleepy105** [comment]
@Arrroz Looks good to you?

**Review by lm-sousa — CHANGES_REQUESTED** [review]
The current limiting resistor most not be global for all rows. Each row should have it's own.

**Review by G-Pereira — APPROVED** [review]
Changes were made

**Pull request merged**
