### PR TITLE
Fixes #39 - Add 256kB EEPROM to the project

### LINKED ISSUE #39: Add EEPROM
High performance STM32 MCU doesn't feature an EEPROM. This can be useful for configurations. Pick one EEPROM chip and design a circuit to connect it to the MCU

### PR DESCRIPTION
**Pull request by lm-sousa**

### CODE REVIEW

**Comment by G-Pereira** [comment]
According to Application note AN1028 WP can't be left floating and both I2C pins and WP should have a pull-up

**Review by G-Pereira — DISMISSED** [review]

**Comment by lm-sousa** [comment]
WP already has a solder jumper to Vcc or GND as required. The Pull-up resistor is redundant in this situation and would lead to unnecessary power usage when WP is pulled low

**Comment by G-Pereira** [comment]
I prefer to size more carefully that pull up to draw less power for two reasons: 
1. AN recommends it to keep it off on reset and power on procedures
2. Device consume considerably more when not in standby (WP = HIGH)

**Comment by G-Pereira** [comment]
"For  the  MSOP  package  only,  pins  A0  and  A1  are  not connected."

UPDATE: the device is confirmed to be a SOIC

**Review by G-Pereira — APPROVED** [review]
All good! Thanks!

**Comment by lm-sousa** [comment]
## AN1028:
## Ax pins
> (...) these inputs must be hard-wired to either logic ‘0’or logic ‘1’. That is, they cannot be left floating, other-wise the device will not operate correctly. 

Those pull-up resistors do not allow the pins to be at  a logic '0'.

### WP pin
> If the designer chooses not to control the WP pin, but rather to always disable write protection, the pin must be hard-wired to logic ‘0’. As with the Chip Address inputs, this pin cannot be left floating, otherwise the device will not operate correctly.

That pull-up resistor does not allow the pin to be at a logic '0' and, therefore, writing to the EEPROM is never allowed.

### I2C bus pull-up resistors
A pull-up resistor was alreay present on the SDA line, however as this notes, it is recomended to use external pull-up resistors on both bus lines. That I can give credit for.
> For I2C the pull up function should be determined by the external pull up resistors and the internal pull up pull down resistors should be disabled.

That is why we have a review process, so people don't undo good work and merge wrong circuitry.
This could all have been avoided if you would have just pointed out that a decoupling capacitor and a pull-up on the SCL line were recommended by the manufacturer. That's the reason there is a review process **with 2 mandatory reviewers**. So that small neglects get corrected, instead of a single person saying 'this is wrong', screwing up the circuit and then circumventing the review process altogether.

Now a major rewrite of the git repo is needed as well as rebases on other branches.

**Comment by G-Pereira** [comment]
Although you're right about the review process, the circuit is correct and similar to what you've done, nothing was thrown away.
WP has a pull up and is controlled by MCU, so if MCU drives the pin LOW, naturally WP goes to LOW.
About Ax pins, there are no pull up resistors on that pins, those are 0 ohm resistors for hw config. Although the application note (encapsulates a lot of IC) says it has to be connected to either high or low, the datasheet state that there is an internal pull down so it's only needed to connect to VCC when needed to pull it HIGH

**Comment by G-Pereira** [comment]
The reason I've been merging and needing only 1 approval (when I do something entirely new I don't commit directly, note I am working on a separate branch because of that) is that it is inducing an enormous delay in the development process since there's low activity and when it gets the approvals most probably won't merge nicely with other PRs that pilled up. This happened in the past and gave a stupid amount of work looking at diffs.
This is not ideal, I know, but essential to keep the project moving.

**Comment by G-Pereira** [comment]
About rebases, that is obviously at the responsibility of the "branch owner". However, I care about other people's work and to help I happily rebase all other branches and make sure they stay safe. There's nothing I can do on secret branches of course (branches that lie only on a personal computer). I don't see the point on not pushing work in progress branches even though there's unfinished, unpolished or still in evaluation ideas. There's a handful of advantages on pushing it to GitHub so others can see what is being done and discuss.

**Pull request merged**
